CREATE TABLE user_action (
	id		BIGINT NOT NULL AUTO_INCREMENT,
	from_uid	VARCHAR(20) NOT NULL,
	to_uid	VARCHAR(20) NOT NULL,
	at_num	VARCHAR(10),
	retweet_num	VARCHAR(10),
  comment_num	VARCHAR(10),
	PRIMARY KEY	(id)) ENGINE=INNODB;
CREATE TABLE user_key_word (
	id		BIGINT NOT NULL AUTO_INCREMENT,
	uid	VARCHAR(20) NOT NULL,
  key_word	TEXT,
	PRIMARY KEY	(id)) ENGINE=INNODB;
CREATE TABLE user_profile (
	id		BIGINT NOT NULL AUTO_INCREMENT,
	uid	VARCHAR(20) NOT NULL,
	user_year	VARCHAR(10) NOT NULL,
	user_sex	VARCHAR(5),
	tweet_num	VARCHAR(10),
  user_tags	VARCHAR(100),
	PRIMARY KEY	(id)) ENGINE=INNODB;
CREATE TABLE user_sns (
	id		BIGINT NOT NULL AUTO_INCREMENT,
	follower_uid	VARCHAR(20) NOT NULL,
	followee_uid	VARCHAR(20) NOT NULL,
	PRIMARY KEY	(id)) ENGINE=INNODB;
CREATE TABLE item (
	id		BIGINT NOT NULL AUTO_INCREMENT,
	item_id	VARCHAR(20) NOT NULL,
	item_cat	VARCHAR(100) NOT NULL,
	item_key_word	TEXT,
	PRIMARY KEY	(id)) ENGINE=INNODB;